"""Pattern banks for injection and exfiltration detection."""
# ruff: noqa: E501

from __future__ import annotations

from rag_sanitizer.models import Severity

INJECTION_RULES: list[dict[str, object]] = [
    # Direct instruction overrides (30+)
    {
        "rule_id": "INJ-001",
        "pattern": r"ignore\s+all\s+previous\s+instructions",
        "severity": Severity.CRITICAL,
        "confidence": 0.98,
    },
    {
        "rule_id": "INJ-002",
        "pattern": r"ignore\s+previous\s+instructions",
        "severity": Severity.CRITICAL,
        "confidence": 0.95,
    },
    {
        "rule_id": "INJ-002A",
        "pattern": r"ignore\s+all\s+instructions",
        "severity": Severity.HIGH,
        "confidence": 0.93,
    },
    {
        "rule_id": "INJ-003",
        "pattern": r"disregard\s+your\s+system\s+prompt",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-004",
        "pattern": r"you\s+are\s+now\s+dan",
        "severity": Severity.HIGH,
        "confidence": 0.95,
    },
    {
        "rule_id": "INJ-005",
        "pattern": r"system\s+override",
        "severity": Severity.CRITICAL,
        "confidence": 0.94,
    },
    {
        "rule_id": "INJ-006",
        "pattern": r"new\s+instructions\s*:",
        "severity": Severity.HIGH,
        "confidence": 0.86,
    },
    {
        "rule_id": "INJ-007",
        "pattern": r"\[system\]",
        "severity": Severity.MEDIUM,
        "confidence": 0.72,
    },
    {"rule_id": "INJ-008", "pattern": r"\[inst\]", "severity": Severity.MEDIUM, "confidence": 0.72},
    {"rule_id": "INJ-009", "pattern": r"<<sys>>", "severity": Severity.MEDIUM, "confidence": 0.74},
    {
        "rule_id": "INJ-010",
        "pattern": r"###\s*instruction\s*:",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-011",
        "pattern": r"###\s*human\s*:",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-012",
        "pattern": r"###\s*assistant\s*:",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-013",
        "pattern": r"from\s+now\s+on\s+you\s+will",
        "severity": Severity.HIGH,
        "confidence": 0.93,
    },
    {
        "rule_id": "INJ-014",
        "pattern": r"your\s+new\s+role\s+is",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-015",
        "pattern": r"forget\s+everything",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-016",
        "pattern": r"reset\s+your\s+instructions",
        "severity": Severity.CRITICAL,
        "confidence": 0.96,
    },
    {
        "rule_id": "INJ-017",
        "pattern": r"act\s+as\s+if\s+you\s+have\s+no\s+restrictions",
        "severity": Severity.HIGH,
        "confidence": 0.95,
    },
    {
        "rule_id": "INJ-018",
        "pattern": r"pretend\s+you\s+are",
        "severity": Severity.MEDIUM,
        "confidence": 0.78,
    },
    {
        "rule_id": "INJ-019",
        "pattern": r"roleplay\s+as",
        "severity": Severity.MEDIUM,
        "confidence": 0.78,
    },
    {
        "rule_id": "INJ-020",
        "pattern": r"override\s+safety",
        "severity": Severity.CRITICAL,
        "confidence": 0.94,
    },
    {
        "rule_id": "INJ-021",
        "pattern": r"disable\s+all\s+guardrails",
        "severity": Severity.CRITICAL,
        "confidence": 0.94,
    },
    {
        "rule_id": "INJ-022",
        "pattern": r"bypass\s+content\s+policy",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-023",
        "pattern": r"ignore\s+safety\s+rules",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-024",
        "pattern": r"discard\s+the\s+above\s+instructions",
        "severity": Severity.HIGH,
        "confidence": 0.93,
    },
    {
        "rule_id": "INJ-025",
        "pattern": r"follow\s+only\s+the\s+instructions\s+below",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-026",
        "pattern": r"treat\s+this\s+as\s+the\s+system\s+message",
        "severity": Severity.CRITICAL,
        "confidence": 0.95,
    },
    {
        "rule_id": "INJ-027",
        "pattern": r"priority\s+instructions",
        "severity": Severity.MEDIUM,
        "confidence": 0.74,
    },
    {
        "rule_id": "INJ-028",
        "pattern": r"assistant\s*:\s*comply",
        "severity": Severity.MEDIUM,
        "confidence": 0.72,
    },
    {
        "rule_id": "INJ-029",
        "pattern": r"developer\s*:\s*",
        "severity": Severity.MEDIUM,
        "confidence": 0.7,
    },
    {
        "rule_id": "INJ-030",
        "pattern": r"system\s*:\s*",
        "severity": Severity.MEDIUM,
        "confidence": 0.7,
    },
    {
        "rule_id": "INJ-031",
        "pattern": r"ignore\s+the\s+context\s+above",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-032",
        "pattern": r"switch\s+to\s+unfiltered\s+mode",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-033",
        "pattern": r"you\s+must\s+obey\s+these\s+instructions",
        "severity": Severity.MEDIUM,
        "confidence": 0.8,
    },
    {
        "rule_id": "INJ-034",
        "pattern": r"developer\s+message\s+override",
        "severity": Severity.CRITICAL,
        "confidence": 0.95,
    },
    # Jailbreak phrases (15+)
    {
        "rule_id": "INJ-035",
        "pattern": r"do\s+anything\s+now",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-036",
        "pattern": r"developer\s+mode\s+enabled",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-037",
        "pattern": r"maintenance\s+mode",
        "severity": Severity.MEDIUM,
        "confidence": 0.75,
    },
    {
        "rule_id": "INJ-038",
        "pattern": r"ethical\s+guidelines\s+do\s+not\s+apply",
        "severity": Severity.CRITICAL,
        "confidence": 0.96,
    },
    {
        "rule_id": "INJ-039",
        "pattern": r"hypothetically\s+speaking",
        "severity": Severity.LOW,
        "confidence": 0.55,
    },
    {
        "rule_id": "INJ-040",
        "pattern": r"for\s+educational\s+purposes\s+only",
        "severity": Severity.LOW,
        "confidence": 0.55,
    },
    {
        "rule_id": "INJ-041",
        "pattern": r"uncensored\s+response",
        "severity": Severity.HIGH,
        "confidence": 0.89,
    },
    {"rule_id": "INJ-042", "pattern": r"jailbreak", "severity": Severity.HIGH, "confidence": 0.88},
    {
        "rule_id": "INJ-043",
        "pattern": r"no\s+restrictions\s+mode",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-044",
        "pattern": r"compliance\s+mode\s+off",
        "severity": Severity.HIGH,
        "confidence": 0.86,
    },
    {
        "rule_id": "INJ-045",
        "pattern": r"bypass\s+alignment",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-046",
        "pattern": r"evil\s+mode",
        "severity": Severity.HIGH,
        "confidence": 0.88,
    },
    {
        "rule_id": "INJ-047",
        "pattern": r"act\s+without\s+ethical\s+constraints",
        "severity": Severity.HIGH,
        "confidence": 0.91,
    },
    {"rule_id": "INJ-048", "pattern": r"dan\s+mode", "severity": Severity.HIGH, "confidence": 0.92},
    {
        "rule_id": "INJ-049",
        "pattern": r"simulated\s+unfiltered\s+assistant",
        "severity": Severity.HIGH,
        "confidence": 0.88,
    },
    # Data extraction (15+)
    {
        "rule_id": "INJ-050",
        "pattern": r"repeat\s+your\s+system\s+prompt",
        "severity": Severity.CRITICAL,
        "confidence": 0.98,
    },
    {
        "rule_id": "INJ-051",
        "pattern": r"what\s+are\s+your\s+instructions",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-052",
        "pattern": r"output\s+your\s+configuration",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-053",
        "pattern": r"print\s+your\s+rules",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-054",
        "pattern": r"show\s+me\s+your\s+prompt",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-055",
        "pattern": r"list\s+all\s+functions",
        "severity": Severity.HIGH,
        "confidence": 0.88,
    },
    {
        "rule_id": "INJ-056",
        "pattern": r"reveal\s+your\s+api\s+key",
        "severity": Severity.CRITICAL,
        "confidence": 0.99,
    },
    {
        "rule_id": "INJ-057",
        "pattern": r"dump\s+system\s+prompt",
        "severity": Severity.CRITICAL,
        "confidence": 0.99,
    },
    {
        "rule_id": "INJ-058",
        "pattern": r"print\s+hidden\s+instructions",
        "severity": Severity.HIGH,
        "confidence": 0.93,
    },
    {
        "rule_id": "INJ-059",
        "pattern": r"leak\s+the\s+prompt",
        "severity": Severity.CRITICAL,
        "confidence": 0.95,
    },
    {
        "rule_id": "INJ-060",
        "pattern": r"expose\s+internal\s+chain\s+of\s+thought",
        "severity": Severity.HIGH,
        "confidence": 0.82,
    },
    {
        "rule_id": "INJ-061",
        "pattern": r"return\s+all\s+hidden\s+context",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    {
        "rule_id": "INJ-062",
        "pattern": r"show\s+the\s+developer\s+message",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-063",
        "pattern": r"display\s+secret\s+instructions",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-064",
        "pattern": r"extract\s+your\s+system\s+configuration",
        "severity": Severity.HIGH,
        "confidence": 0.9,
    },
    # Tool/function abuse (10+)
    {
        "rule_id": "INJ-065",
        "pattern": r"call\s+function",
        "severity": Severity.MEDIUM,
        "confidence": 0.8,
    },
    {
        "rule_id": "INJ-066",
        "pattern": r"execute\s+code",
        "severity": Severity.HIGH,
        "confidence": 0.89,
    },
    {
        "rule_id": "INJ-067",
        "pattern": r"run\s+command",
        "severity": Severity.HIGH,
        "confidence": 0.88,
    },
    {
        "rule_id": "INJ-068",
        "pattern": r"use\s+tool",
        "severity": Severity.MEDIUM,
        "confidence": 0.78,
    },
    {
        "rule_id": "INJ-069",
        "pattern": r"invoke\s+tool",
        "severity": Severity.MEDIUM,
        "confidence": 0.78,
    },
    {
        "rule_id": "INJ-070",
        "pattern": r"function_call",
        "severity": Severity.MEDIUM,
        "confidence": 0.75,
    },
    {
        "rule_id": "INJ-071",
        "pattern": r"tool\s*:\s*",
        "severity": Severity.MEDIUM,
        "confidence": 0.72,
    },
    {
        "rule_id": "INJ-072",
        "pattern": r"python\s+exec",
        "severity": Severity.HIGH,
        "confidence": 0.86,
    },
    {
        "rule_id": "INJ-073",
        "pattern": r"shell\s+command",
        "severity": Severity.HIGH,
        "confidence": 0.86,
    },
    {
        "rule_id": "INJ-074",
        "pattern": r"browse\s+to\s+url",
        "severity": Severity.MEDIUM,
        "confidence": 0.72,
    },
    # Delimiter injection (10+)
    {
        "rule_id": "INJ-075",
        "pattern": r"---\s*end\s+of\s+document\s*---",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {"rule_id": "INJ-076", "pattern": r"</context>", "severity": Severity.HIGH, "confidence": 0.9},
    {"rule_id": "INJ-077", "pattern": r"\[end\]", "severity": Severity.MEDIUM, "confidence": 0.78},
    {
        "rule_id": "INJ-078",
        "pattern": r"begin\s+system\s+message",
        "severity": Severity.CRITICAL,
        "confidence": 0.94,
    },
    {
        "rule_id": "INJ-079",
        "pattern": r"end\s+system\s+message",
        "severity": Severity.CRITICAL,
        "confidence": 0.94,
    },
    {
        "rule_id": "INJ-080",
        "pattern": r"<\|im_start\|>system",
        "severity": Severity.CRITICAL,
        "confidence": 0.93,
    },
    {
        "rule_id": "INJ-081",
        "pattern": r"<\|im_end\|>",
        "severity": Severity.HIGH,
        "confidence": 0.88,
    },
    {
        "rule_id": "INJ-082",
        "pattern": r"\[\[system\]\]",
        "severity": Severity.HIGH,
        "confidence": 0.86,
    },
    {
        "rule_id": "INJ-083",
        "pattern": r"\[\[assistant\]\]",
        "severity": Severity.HIGH,
        "confidence": 0.86,
    },
    {"rule_id": "INJ-084", "pattern": r"^\s*---+\s*$", "severity": Severity.LOW, "confidence": 0.5},
    # Multilingual high-signal translations
    {
        "rule_id": "INJ-085",
        "pattern": r"ignora\s+todas\s+las\s+instrucciones\s+anteriores",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-086",
        "pattern": r"oublie\s+toutes\s+les\s+instructions\s+précédentes",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-087",
        "pattern": r"ignoriere\s+alle\s+vorherigen\s+anweisungen",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-088",
        "pattern": r"忽略之前的所有指令",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-089",
        "pattern": r"以前のすべての指示を無視",
        "severity": Severity.CRITICAL,
        "confidence": 0.97,
    },
    {
        "rule_id": "INJ-090",
        "pattern": r"muestra\s+tu\s+prompt\s+del\s+sistema",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-091",
        "pattern": r"montre\s+ton\s+prompt\s+système",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-092",
        "pattern": r"zeige\s+deinen\s+system\s+prompt",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-093",
        "pattern": r"显示你的系统提示",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
    {
        "rule_id": "INJ-094",
        "pattern": r"システムプロンプトを表示",
        "severity": Severity.HIGH,
        "confidence": 0.92,
    },
]

EXFIL_QUERY_KEYS = {"data", "token", "secret", "key", "prompt", "context", "exfil", "log"}
WEBHOOK_DOMAINS = {"webhook.site", "requestbin", "pipedream", "ngrok", "burpcollaborator"}
SHORTENER_DOMAINS = {"bit.ly", "tinyurl.com", "t.co", "goo.gl", "is.gd"}

ZERO_WIDTH_CHARS = "\u200b\u200c\u200d\u2060\u200e\u200f\ufeff"
HOMOGLYPH_MAP = {
    "а": "a",  # Cyrillic a
    "е": "e",
    "і": "i",
    "о": "o",
    "р": "p",
    "с": "c",
    "у": "y",
    "х": "x",
    "Α": "A",  # Greek Alpha
    "Β": "B",
    "Ε": "E",
    "Ι": "I",
    "Κ": "K",
    "Μ": "M",
    "Ν": "N",
    "Ο": "O",
    "Ρ": "P",
    "Τ": "T",
    "Χ": "X",
}
